# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        always-auth: false
    
    - name: Check and remove ~/.npmrc
      run: |
        if [ -f ~/.npmrc ]; then cat ~/.npmrc; rm ~/.npmrc; fi
    
    - name: Check and remove project-level .npmrc
      run: |
        if [ -f .npmrc ]; then cat .npmrc; rm .npmrc; fi
    
    - name: Clear npm token env vars
      run: |
        unset NODE_AUTH_TOKEN
        unset NPM_TOKEN
    
    - name: Install dependencies
      run: npm ci

    - name: Test format with lint
      run: npm run lint

    - name: Test unit cases with jest
      run: npm test

    - name: Build
      run: npm run build --if-present

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run E2E Tests
      run: npm run e2e
